use nohup for target starting, add jampy m1 conformance and readme badge

diff --git a/.github/workflows/conformance.yaml b/.github/workflows/conformance.yaml
--- a/.github/workflows/conformance.yaml
+++ b/.github/workflows/conformance.yaml
@@ -36,14 +36,16 @@ jobs:
       - name: Start jampy-target
         run: |
           cd ./jampy-target/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
-          setsid ./jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock &
+          nohup ./jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock > ${{ github.workspace }}/target.log 2>&1 &
           echo $! > ${{ github.workspace }}/target.pid
           sleep 3
           for i in 1 2 3 4 5; do
             [ -S ${{ github.workspace }}/jam_target.sock ] && echo "Socket ready" && exit 0
             sleep 1
           done
-          echo "Socket not found" && exit 1
+          echo "Socket not found"
+          cat ${{ github.workspace }}/target.log
+          exit 1
 
       - name: Run fuzzer on conformance traces
         run: |
