start the target in single cis

diff --git a/.github/workflows/minifuzz.yaml b/.github/workflows/minifuzz.yaml
--- a/.github/workflows/minifuzz.yaml
+++ b/.github/workflows/minifuzz.yaml
@@ -38,6 +38,18 @@ jobs:
       - name: Clone jam-conformance
         run: git clone https://github.com/davxy/jam-conformance
 
+      - name: Start jampy-target
+        run: |
+          cd ./jampy-target/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
+          setsid ./jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock &
+          echo $! > ${{ github.workspace }}/target.pid
+          sleep 3
+          for i in 1 2 3 4 5; do
+            [ -S ${{ github.workspace }}/jam_target.sock ] && echo "Socket ready" && exit 0
+            sleep 1
+          done
+          echo "Socket not found" && exit 1
+
       - name: Run fuzzer on minifuzz examples - no_forks
         run: |
           python jam-conformance/fuzz-proto/minifuzz/minifuzz.py -d jam-conformance/fuzz-proto/examples/${{ env.JAM_VERSION }}/no_forks -s ${{ github.workspace }}/jam_target.sock
